// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SportServiceClient is the client API for SportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SportServiceClient interface {
	GetAllTeams(ctx context.Context, in *AllTeamsRequest, opts ...grpc.CallOption) (*TeamsResponse, error)
}

type sportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSportServiceClient(cc grpc.ClientConnInterface) SportServiceClient {
	return &sportServiceClient{cc}
}

func (c *sportServiceClient) GetAllTeams(ctx context.Context, in *AllTeamsRequest, opts ...grpc.CallOption) (*TeamsResponse, error) {
	out := new(TeamsResponse)
	err := c.cc.Invoke(ctx, "/sport.SportService/GetAllTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SportServiceServer is the server API for SportService service.
// All implementations must embed UnimplementedSportServiceServer
// for forward compatibility
type SportServiceServer interface {
	GetAllTeams(context.Context, *AllTeamsRequest) (*TeamsResponse, error)
	mustEmbedUnimplementedSportServiceServer()
}

// UnimplementedSportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSportServiceServer struct {
}

func (UnimplementedSportServiceServer) GetAllTeams(context.Context, *AllTeamsRequest) (*TeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTeams not implemented")
}
func (UnimplementedSportServiceServer) mustEmbedUnimplementedSportServiceServer() {}

// UnsafeSportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SportServiceServer will
// result in compilation errors.
type UnsafeSportServiceServer interface {
	mustEmbedUnimplementedSportServiceServer()
}

func RegisterSportServiceServer(s grpc.ServiceRegistrar, srv SportServiceServer) {
	s.RegisterService(&SportService_ServiceDesc, srv)
}

func _SportService_GetAllTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportServiceServer).GetAllTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sport.SportService/GetAllTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportServiceServer).GetAllTeams(ctx, req.(*AllTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SportService_ServiceDesc is the grpc.ServiceDesc for SportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sport.SportService",
	HandlerType: (*SportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTeams",
			Handler:    _SportService_GetAllTeams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sport.proto",
}
