// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: sport.proto

package sport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Team  string `protobuf:"bytes,3,opt,name=Team,proto3" json:"Team,omitempty"`
	Sport string `protobuf:"bytes,4,opt,name=Sport,proto3" json:"Sport,omitempty"`
}

func (x *TeamResponse) Reset() {
	*x = TeamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamResponse) ProtoMessage() {}

func (x *TeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamResponse.ProtoReflect.Descriptor instead.
func (*TeamResponse) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{0}
}

func (x *TeamResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TeamResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamResponse) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *TeamResponse) GetSport() string {
	if x != nil {
		return x.Sport
	}
	return ""
}

type TeamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teams []*TeamResponse `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *TeamsResponse) Reset() {
	*x = TeamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamsResponse) ProtoMessage() {}

func (x *TeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamsResponse.ProtoReflect.Descriptor instead.
func (*TeamsResponse) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{1}
}

func (x *TeamsResponse) GetTeams() []*TeamResponse {
	if x != nil {
		return x.Teams
	}
	return nil
}

type AllTeamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllTeamsRequest) Reset() {
	*x = AllTeamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sport_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTeamsRequest) ProtoMessage() {}

func (x *AllTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTeamsRequest.ProtoReflect.Descriptor instead.
func (*AllTeamsRequest) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{2}
}

var File_sport_proto protoreflect.FileDescriptor

var file_sport_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x22, 0x5c, 0x0a, 0x0c, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x70, 0x6f,
	0x72, 0x74, 0x22, 0x3a, 0x0a, 0x0d, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x22, 0x11,
	0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x32, 0x4d, 0x0a, 0x0c, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x61, 0x6d, 0x73,
	0x12, 0x16, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x61, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sport_proto_rawDescOnce sync.Once
	file_sport_proto_rawDescData = file_sport_proto_rawDesc
)

func file_sport_proto_rawDescGZIP() []byte {
	file_sport_proto_rawDescOnce.Do(func() {
		file_sport_proto_rawDescData = protoimpl.X.CompressGZIP(file_sport_proto_rawDescData)
	})
	return file_sport_proto_rawDescData
}

var file_sport_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sport_proto_goTypes = []interface{}{
	(*TeamResponse)(nil),    // 0: sport.TeamResponse
	(*TeamsResponse)(nil),   // 1: sport.TeamsResponse
	(*AllTeamsRequest)(nil), // 2: sport.AllTeamsRequest
}
var file_sport_proto_depIdxs = []int32{
	0, // 0: sport.TeamsResponse.teams:type_name -> sport.TeamResponse
	2, // 1: sport.SportService.GetAllTeams:input_type -> sport.AllTeamsRequest
	1, // 2: sport.SportService.GetAllTeams:output_type -> sport.TeamsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sport_proto_init() }
func file_sport_proto_init() {
	if File_sport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sport_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllTeamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sport_proto_goTypes,
		DependencyIndexes: file_sport_proto_depIdxs,
		MessageInfos:      file_sport_proto_msgTypes,
	}.Build()
	File_sport_proto = out.File
	file_sport_proto_rawDesc = nil
	file_sport_proto_goTypes = nil
	file_sport_proto_depIdxs = nil
}
